package package1;

public class TEST1 {
	public static void main(String[] args) {
		
	
	int a=12;
	int b=24;
	System.out.println(a+b);
}

}


/*How to create a git Tocken ID

 GO TO-->GIT ACCOUNT
CLICK ON PROFILE-->SETTINGS
CLICK ON DEVELOPER SETTINGS
CLICK ON PERSONAL ACCES TOCKEN-->SELECT CLASSIC TOKEN
GENETRATE TOKEN SELECT ON CONTENT AVAILABLE (SCOPE,NOTE,EXPIRATION DATE)

*/

/*How to PUSH/UPLOAD PROJECT IN GIT

RIGHT CLICK ON PROJECT-->GO TO TEAM-->SHARE PROJECT
CLICK ON CREATE REPOSITARY-->GIVE BRANCH AS MASTER AND REPOSITARY NAME IF WANT-->CLICK ON FINISH
CHECK FOR CREATION OF GIT IN PROJECT NAME
AGAIN  RIGHT CLICK ON PROJECT-->GO TO TEAM-->PUSH
DRAG TO UNSTANGED TO STAGED-->GIVE MESSAGE IN COMMIT-->CLICK ON COMMIT-->CLICK ON PUSH HEAD
CHECK FOR REPOSITARY NAME AND BRANCH-->CLICK ON PREVIEW
GIVE USER AND PASSWORD(1ST TIME)-->GIVE USER NAME AND PASSWORD AS(BARRER TOKEN ID)2ND TIME-->CLICK ON PREVIEW
GIVE USER NAME AND PASSWORD AS(BARRER TOKEN ID)3RD TIME-->AFTER UPLOADING--> CLICK ON CLOSE

*/
 

//NOTE:WHILE COMMITING FIST IT MUST BE SAVED
